version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_gapsim
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - ai_gapsim_network
    restart: always
    command: python simple_api.py  # Use simple API for quick testing

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_gapsim
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_gapsim_network
    restart: always

volumes:
  postgres_data:

networks:
  ai_gapsim_network:
    driver: bridge 